import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import "./globals.css";
import WebsiteTemplate from "@/templates/WebsiteTemplate";

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
  variable: "--font-oxygen-sans",
});

export const metadata: Metadata = {
  title: "Qultare Collective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oxygen.variable} antialiased`}>
        <WebsiteTemplate>{children}</WebsiteTemplate>
      </body>
    </html>
  );
}
